# Documentation for this file: http://docs.gitlab.com/ce/ci/yaml/

# Setup
# ---------------------------------

# Which Docker image to use
image: "ruby:2.3.1"

# Which Docker services to use
services:
  - postgres:latest

# Build variables
variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  # These variables need to be set for Rails too in database.yml.
  POSTGRES_DB: smart_parking_api_test
  POSTGRES_USER: smart_parking_user
  POSTGRES_PASSWORD: smart_parking_pass

# These commands will run before each job's script
before_script:
  - cp config/database-ci.yml config/database.yml
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle check || bundle install --jobs $(nproc) --path=/cache/bundler
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate

# Additional reserved keywords:
# stages (= types), after_script, cache

# Jobs
# ---------------------------------

# Test database connection to Postgres
connect:
  image: postgres
  before_script:
    - cp config/database-ci.yml config/database.yml
    - which psql
  script:
    # Official way to provide password to psql:
    # http://www.postgresql.org/docs/9.3/static/libpq-envars.html
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

# Run RSpec
rspec:
  script:
    - bundle exec rspec
